# todo

DEBUG_MODE = True

START_DATE = "2022-12-17"
END_DATE = "2022-12-31"

# SAVE_FILTERABLE_COLORS = True
# SAVE_URL = True
# SAVE_MEDIA_TYPE = True

# CREATE_COMBINED_IMAGES = True
# CREATE_FILTERS_PREVIEW = True

# USE_HDURL = False

# CLEAN_TEMP
